DROP TABLE IF EXISTS Member;

CREATE TABLE Member (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	csName VARCHAR (20) NOT NULL, 
	loginStatus VARCHAR (20) NOT NULL, 
	profileID INT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
);